Repository warchivee/warchive-api, pull requests merged in 2024-01, with the labels that each got.

#7 ✨ feat: 카카오 로그인 구현 (#1)
  .gitignore
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/auth/api/auth.controller.spec.ts
  src/auth/api/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/interface/kakaoLoginInfo.interface.ts
  src/auth/interface/kakaoToken.interface.ts
  src/auth/middleware/auth.middlewere.ts
  src/auth/services/auth.service.spec.ts
  src/auth/services/auth.service.ts
  src/auth/strategies/jwt.starategy.ts
  src/user/dto/createUser.dto.ts
  src/user/dto/findUser.dto.ts
  src/user/entities/user.entity.ts
  src/user/user.module.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
Labels: ✨ feature, 🙍🏻‍♀️ data confirm, 🙍🏻‍♀️ user

#11 ✨ feat: 데이터 수정 구현 (#4)
  src/admin/wata/dto/update-wata-label.dto.ts
  src/admin/wata/entities/wata.entity.ts
  src/admin/wata/interface/wata.type.ts
  src/admin/wata/wata.controller.ts
  src/admin/wata/wata.service.ts
  src/common/exception/service.exception.ts
  src/common/interface/error-code.type.ts
Labels: 🙍🏻‍♀️ data confirm, 🔀 pull request

#15 ✨ fefactor: 로그인 시 토큰 응답 body 형태 수정 및 유효시간 환경변수화 (#14)
  src/auth/auth.service.ts
  src/auth/interface/token.interface.ts
  src/auth/jwt.service.ts
Labels: 🙍🏻‍♀️ user, 🔀 pull request

#16 chor: 리프레시 토큰은 httpOnly 쿠키, 액세스 토큰은 response body 로 응답하도록 수정 (#14)
  package.json
  pnpm-lock.yaml
  src/admin/category/dto/create-category.dto.ts
  src/admin/caution/dto/create-caution.dto.ts
  src/admin/genre/dto/create-genre.dto.ts
  src/admin/keyword/dto/create-keyword.dto.ts
  src/admin/platform/dto/create-platform.dto.ts
  src/admin/wata/dto/create-wata.dto.ts
  src/auth/auth.controller.ts
  src/auth/auth.guard.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/login.dto.ts
  src/auth/interface/kakaoLoginInfo.interface.ts
  src/auth/interface/token.interface.ts
  src/auth/jwt.service.ts
  src/main.ts
  src/user/dto/create-user.dto.ts
  src/user/dto/find-user.dto.ts
  src/user/user.service.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
Labels: ♻️ refactor, 🙍🏻‍♀️ user, 🔀 pull request

#17 feat: 데이터 목록 조회 구현 (#3)
  src/admin/wata/dto/find-wata.dto.ts
  src/admin/wata/wata.controller.ts
  src/admin/wata/wata.service.ts
Labels: 🙍🏻‍♀️ data confirm, 🔀 pull request

#20 ✨ feat: 데이터 목록 조회 시 업데이트 기간 필터링 기능 추가, 업데이트 최신순(내림차순) 추가 (#3)
  .gitignore
  src/admin/wata/dto/find-wata.dto.ts
  src/admin/wata/wata.controller.ts
  src/admin/wata/wata.service.ts
  src/app.module.ts
  src/common/entities/common.entity.ts
Labels: 🙍🏻‍♀️ data confirm, 🔀 pull request

#21 ✨ feat: merge 상태를 게시 상태로 변경 (#3)
  src/admin/wata/entities/wata.entity.ts
  src/admin/wata/wata.service.ts
Labels: 🔀 pull request
